import { useMemo, useState, type ChangeEvent, type FormEvent } from "react";
import { backgroundPresets, type BackgroundPresetId } from "./backgrounds/backgroundPresets";
import { cakePresets } from "./cakes/cakePresets";
import type { CakePresetId } from "./cakes/types";
import { businessConfig } from "./giftConfig";

type Tier = "standard" | "premium";
type FormState = { customer: string; recipient: string; tier: Tier; cake: CakePresetId; background: BackgroundPresetId; message: string; photos: string; contact: string; comment: string };
const packages: { id: Tier; name: string; price: string; items: string[] }[] = [
  { id: "standard", name: "Стандарт", price: "2 990 ₸", items: ["Готовые торты и фоны", "До 5 фотографий", "Текст, музыка из коллекции и ссылка", "Одно бесплатное исправление"] },
  { id: "premium", name: "Премиум", price: "4 990 ₸", items: ["Все торты и индивидуальные цвета", "До 12 фотографий и музыка клиента", "Собственный фон и надпись", "Два бесплатных исправления"] },
];
const initial: FormState = { customer: "", recipient: "", tier: "standard", cake: "classic", background: "stars", message: "", photos: "5", contact: "", comment: "" };
const allowed = <T extends { tier: Tier }>(item: T, tier: Tier) => item.tier === "standard" || tier === "premium";

export function LandingPage() {
  const [form, setForm] = useState(initial); const [status, setStatus] = useState("");
  const orderText = useMemo(() => ["Заявка CakeWish", `Заказчик: ${form.customer}`, `Получатель: ${form.recipient}`, `Тариф: ${packages.find((item) => item.id === form.tier)?.name}`, `Торт: ${cakePresets[form.cake].name}`, `Фон: ${backgroundPresets[form.background].name}`, `Текст: ${form.message}`, `Фото: ${form.photos}`, `Связь: ${form.contact}`, `Комментарий: ${form.comment || "нет"}`].join("\n"), [form]);
  const update = (field: keyof FormState) => (event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => { setForm((current) => ({ ...current, [field]: event.target.value })); setStatus(""); };
  const selectTier = (tier: Tier) => setForm((current) => ({ ...current, tier, cake: allowed(cakePresets[current.cake], tier) ? current.cake : "classic", background: allowed(backgroundPresets[current.background], tier) ? current.background : "stars" }));
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); try { await navigator.clipboard.writeText(orderText); setStatus("Заявка скопирована. Открываем чат для отправки."); const separator = businessConfig.orderContactUrl.includes("?") ? "&" : "?"; window.open(`${businessConfig.orderContactUrl}${separator}text=${encodeURIComponent(orderText)}`, "_blank", "noopener,noreferrer"); } catch { setStatus("Не удалось скопировать текст. Выберите и скопируйте данные вручную."); } };
  return <main className="landing-page"><section className="hero-section"><nav className="site-nav" aria-label="Навигация"><a className="brand" href="/">{businessConfig.brandName}</a><div className="nav-links"><a href="/g/demo">Демо</a><a href="#order">Заказать</a></div></nav><div className="hero-grid"><div className="hero-copy"><p className="eyebrow">Интерактивное поздравление</p><h1>3D-подарок на день рождения по персональной ссылке</h1><p className="hero-description">Фото, музыка, свеча, торт и финальное поздравление в одном тёплом сюрпризе, который удобно открыть с телефона.</p><div className="hero-actions"><a className="primary-action" href="/g/demo">Открыть демо</a><a className="secondary-action" href="#order">Выбрать дизайн</a></div></div><div className="hero-preview"><div className="phone-frame"><span>{businessConfig.domainExample}/g/ваш-сюрприз</span><div className="cake-orb">🎂</div><p>Нажмите, чтобы открыть</p></div></div></div></section>
    <section className="packages-section" aria-label="Тарифы">{packages.map((item) => <button type="button" className={`package-card ${form.tier === item.id ? "is-selected" : ""}`} key={item.id} onClick={() => selectTier(item.id)} aria-pressed={form.tier === item.id}><div><h2>{item.name}</h2>{item.items.map((line) => <p key={line}>{line}</p>)}</div><strong>{item.price}</strong><span>{form.tier === item.id ? "Выбрано" : "Выбрать тариф"}</span></button>)}</section>
    <section className="style-preview-section"><div className="section-heading"><p className="eyebrow">Реальные дизайны</p><h2>Выберите торт и фон</h2><p>Эти же пресеты используются внутри 3D-поздравления.</p></div><div className="preview-group"><h3>Торт</h3><div className="preview-card-grid">{Object.values(cakePresets).filter((preset) => allowed(preset, form.tier)).map((preset) => <button className={`option-preview cake-preview ${preset.id} ${form.cake === preset.id ? "is-selected" : ""}`} key={preset.id} type="button" onClick={() => setForm((current) => ({ ...current, cake: preset.id }))} aria-pressed={form.cake === preset.id}><span className="option-visual" aria-hidden="true" /><span className="option-title">{preset.name}</span><span className="option-description">{preset.description}</span><small>{preset.tier === "premium" ? "Премиум" : "Стандарт"}</small></button>)}</div></div><div className="preview-group"><h3>Фон</h3><div className="preview-card-grid">{Object.values(backgroundPresets).filter((preset) => allowed(preset, form.tier)).map((preset) => <button className={`option-preview background-preview ${preset.id} ${form.background === preset.id ? "is-selected" : ""}`} key={preset.id} type="button" onClick={() => setForm((current) => ({ ...current, background: preset.id }))} aria-pressed={form.background === preset.id}><span className="option-visual" style={{ background: preset.fallbackGradient }} aria-hidden="true" /><span className="option-title">{preset.name}</span><span className="option-description">{preset.description}</span><small>{preset.tier === "premium" ? "Премиум" : "Стандарт"}</small></button>)}</div></div></section>
    <section className="order-section" id="order"><div className="order-copy"><p className="eyebrow">Заявка</p><h2>Расскажите о будущем подарке</h2><p>Форма подготовит структурированный текст и откроет выбранный канал связи. Фото отправляются в чат после заявки.</p></div><form className="order-form" onSubmit={submit}><div className="form-row"><label>Ваше имя<input required value={form.customer} onChange={update("customer")} /></label><label>Имя получателя<input required value={form.recipient} onChange={update("recipient")} /></label></div><label>Поздравительный текст<textarea required rows={4} value={form.message} onChange={update("message")} /></label><div className="form-row"><label>Количество фотографий<input required min="1" max={form.tier === "premium" ? 12 : 5} type="number" value={form.photos} onChange={update("photos")} /></label><label>Ссылка или способ связи<input required value={form.contact} onChange={update("contact")} placeholder="Telegram, WhatsApp или телефон" /></label></div><label>Комментарий<textarea rows={3} value={form.comment} onChange={update("comment")} /></label><p className="field-note">Выбрано: {cakePresets[form.cake].name}, {backgroundPresets[form.background].name}, {packages.find((item) => item.id === form.tier)?.name}.</p><button className="primary-action" type="submit">Скопировать и открыть чат</button>{status && <p className="form-status" role="status">{status}</p>}</form></section></main>;
}
