import type { CakePreset, CakePresetId } from "./types";

export const cakePresets: Record<CakePresetId, CakePreset> = {
  romantic: { id: "romantic", name: "Романтический", description: "Нежный крем, ягоды, розы и сердца", tier: "standard", layers: ["#c84f7b", "#efadc5"], frosting: "#fff3e8", decoration: "flowers", decorationColor: "#a92f5b", candleCount: 4, candleColor: "#efadc5", flameColor: "#ffd36a", glow: 0.7, scale: 1, renderMode: "procedural", modelUrl: "/models/cakes/romantic-v1.glb", fallbackPreset: "romantic", decorations: { berries: true, hearts: true, flowers: true, gold: true } },
  classic: { id: "classic", name: "Классический", description: "Ваниль, ягодная прослойка и посыпка", tier: "standard", layers: ["#7d3f47", "#f7d995", "#ffeac3"], frosting: "#fffaf0", decoration: "sprinkles", decorationColor: "#50bce8", candleCount: 3, candleColor: "#67c9ec", flameColor: "#ffd65a", glow: 0.55, scale: 1, renderMode: "procedural", modelUrl: "/models/cakes/classic-v1.glb", fallbackPreset: "classic", decorations: { sprinkles: true } },
  luxury: { id: "luxury", name: "Люкс", description: "Тёмный шоколад и минималистичное золото", tier: "premium", layers: ["#24181c", "#3a2726"], frosting: "#e9d3a7", decoration: "gold", decorationColor: "#dcb55b", candleCount: 1, candleColor: "#dcb55b", flameColor: "#fff0a7", glow: 0.85, scale: 1.02, renderMode: "procedural", modelUrl: "/models/cakes/luxury-v1.glb", fallbackPreset: "luxury", decorations: { gold: true } },
  cosmic: { id: "cosmic", name: "Космический", description: "Синие слои, звёзды и мягкое свечение", tier: "premium", layers: ["#171a4d", "#33246f"], frosting: "#a990e9", decoration: "stars", decorationColor: "#9ee7ff", candleCount: 2, candleColor: "#9ee7ff", flameColor: "#91dcff", glow: 1.1, scale: 1.02, renderMode: "procedural", modelUrl: "/models/cakes/cosmic-v1.glb", fallbackPreset: "cosmic", decorations: { stars: true } },
  rainbow: { id: "rainbow", name: "Радужный", description: "Настоящие яркие слои и крем", tier: "standard", layers: ["#f35f8b", "#ffbd59", "#ffe66d", "#63c985", "#5ca9ee"], frosting: "#fff9ed", decoration: "rainbow", decorationColor: "#9368df", candleCount: 3, candleColor: "#ffbf59", flameColor: "#fff17e", glow: 0.65, scale: 1, renderMode: "procedural", modelUrl: "/models/cakes/rainbow-v1.glb", fallbackPreset: "rainbow", decorations: { sprinkles: true } },
};
